baseurl = "https://www.belchak.com/"
languageCode = "en-us"
googleAnalytics = "G-VRDG72H6Z7"

[pagination]
pagerSize = 5

[params]
contentTypeName = "post"
themeColor = "green"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true
readingTime = true
showLanguageSelector = false


[languages]
[languages.en]
title = "belchak.com"
subtitle = "A blog"
keywords = "blog"
copyright = "&copy; Copyright Ben Belchak"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "belchak.com"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/post"

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"

[module]
# this is needed when you fetch the theme as a submodule to your repo.
# replacements = "github.com/panr/hugo-theme-terminal/4 -> themes/terminal"
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
