baseurl = "https://www.belchak.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-20863470-1"
disqusShortname = "belchakcom"

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "belchak.com"
    subtitle = "A blog"
    keywords = ""
    copyright = "&copy; Copyright Ben Belchak"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "belchak.com"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"

      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
    
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
